### PR TITLE
Add (interactive and non-interactive) simulator

### LINKED ISSUE #5: Simulator interface: interactive and non-interactive simulation
In DifferentialEquations.jl, there are two interfaces: integrator (interactive) and solve (non-interactive; compatible with callbacks).

In FSimBase.jl, solve interface is already provided as `sim`. If the interactive simulation interface is provided, it will be useful especially for simulations with communication, e.g., ROS2-compatible simulation and with parameters varying periodically, e.g., zero-order-hold control and model predictive control for continuous systems.

Next goal:
1) Provide a unified "Simulator" struct with which users can perform either interactive or non-interactive simulation.
2) Rename `sim` as `solve`.
3) Add an interactive simulation interface.

After this work, the version of FlightSims.jl would be v1.0.0 :)

### LINKED ISSUE #7: Provide discrete problem
See [DiscreteProblem](https://diffeq.sciml.ai/stable/types/discrete_types/#Discrete-Problems) in DiffEq.jl.

### PR DESCRIPTION
**Pull request by JinraeKim**
Resolves #1 and #7.

### CODE REVIEW

**Comment by JinraeKim** [comment]
@hnlee77, @nhcho91

I finished works to resolve #5.
As I said, it will be the official release (v1.0.0) of FlightSims.jl.
Main functionality has been tested with the test scripts of FlightSims.jl.
However, there may still exist some awkward usage pattern or potential bugs.

Could you guys review the update in #6?

You would be able to test codes with "the branch of FSimBase.jl, #6" and "the branch of [FlightSims.jl, #141](https://github.com/JinraeKim/FlightSims.jl/pull/141)".

Please read the `README.md` in the branch of FlightSims.jl and other source files :)

**Comment by nhcho91** [comment]
No serious issues have been identified so far regarding compatibility with FlightGNC.jl :)

**Comment by JinraeKim** [comment]
It is planned to be merged after a test period.

**Comment by JinraeKim** [comment]
Update compat for [the bug fix of `SimulationLogger`](https://github.com/JinraeKim/SimulationLogger.jl/pull/8) if necessary.

**Comment by JinraeKim** [comment]
To control saving and step behaviours in detail, I detached `df` argument from `step!` and `step_until!`.
Instead, use `push!`.
See the revised `README.md`.

### Why is it necessary?
As shown in `test/minimal.jl`, I'd like to reject "a state which is out of a given bound".

**Comment by nhcho91** [comment]
> Update compat for [the bug fix of `SimulationLogger`](https://github.com/JinraeKim/SimulationLogger.jl/pull/8) if necessary.

Do you mean the compat written in project.toml?

**Comment by JinraeKim** [comment]
> Do you mean the compat written in project.toml?

The comment is just a reminder to me :) Never mind.

**Pull request merged**
